### ISSUE TITLE
Optimize package.json

### ISSUE THREAD

**Issue by hesselberg** [Novicell/novicell-frontend#11]
Look for redundancies in the package.json, specifically jshint.

**Comment by Dan9boi** [comment]
@hesselberg maybe we should look at jslint?
also check for updates in node packages.

**Comment by hesselberg** [comment]
@Dan9boi I agree :)

**Comment by Dan9boi** [comment]
As of this commit https://github.com/Novicell/novicell-frontend/commit/a83ae85faa99c6613a42465874a890b4ba71dd8a i've updated every node module in The package.json.
And As of this PR https://github.com/Novicell/novicell-frontend/pull/35 i've added reporters to jscs and jshint, so that it gives warnings about better js and codestyle.

It looks like jshint is the superior version of jslint, so we're gonna stick to jshint.
Gulp-jshint needs manual dependency of the jshint node module, and thats why it seems to appear twice in the package.json.
