### ISSUE TITLE
Remove bower

### ISSUE THREAD

**Issue by camaya** [Novicell/novicell-frontend#64]
Hi,

I think nowadays bower is kind of obsolete as you can find all your frontend packages on npm.
So I propose we get rid of bower. The advantage is one tool less which means less config.

What do you think?

Cheers,
Cristhian.

**Comment by Dan9boi** [comment]
I see what you are saying, but in my world it is a question of _seperation of concerns_.
NPM is modules for the build tool, where bower is for frontend dependencies.
This helps the developer know where to look for frontend dependencies and doesn't have to look in the node_modules folder, as it is just for the build tool.

We already have gulp running bower, with the `gulp-bower` module, as for keeping it simple.

**Comment by camaya** [comment]
Hi Dani,

I understand your point, but I don't completely agree.
I'm all in for separation of concerns, but as I see it, the concern with bower is install frontend packages which npm is 100% capable of doing.
Also, I see that having just one tool is simpler than having two tools which means more configuration and dependencies, but I get that replacing bower with npm now means more work taking into account that everything is already configured so feel free to close this.

Cheers,
Cristhian.

**Comment by Dan9boi** [comment]
No further comments? Then we are going to close this...

**Comment by Dan9boi** [comment]
@marklonquist

**Comment by Dan9boi** [comment]
Bower is losing it's take as the package manager for frontend libraries. This is getting more clear as the angular team has stated that angular 2, will never be available through bower (https://github.com/angular/angular/issues/4018).

This means a lot, as the winning argument for keeping bower is _separation of concerns_. This is not any longer a valid argument, as angular 2 will only be available through npm.

We have some things to fix before removing bower completely, but I'm convinced that it is the way to go.
By using `gulp-bower` we can make gulp run `bower install` and help backenders only run one command, for building the frontend.

**Things we need to fix:**
- [ ] Find a way to run `npm install` together with `gulp`, for backenders
- [ ] Document how to use npm instead of bower. What is changed and how should i do now.

**Comment by hesselberg** [comment]
@Dan9boi `Find a way to run npm install together with gulp, for backenders` doesn't really make sense? You have to run npm install to get gulp up and running. I guess the "1 line to rule them all" would just be to chain the commands.
`npm install && gulp`

**Comment by marklonquist** [comment]
I understand what @Dan9boi means - In case new dependencies are added to the project, how will someone who updates through the repository know that these dependencies has been added.. With bower, they were installed automatically when running gulp.

**Comment by hesselberg** [comment]
Chaining the commands would solve that issue, but I see your point. 
Another thing comes to mind; if the developer running the command isn't administrator, the npm install might not have access to writing new folders. I.e. runas/sudo commands might be needed.

**Comment by Dan9boi** [comment]
@soreng did you have some input about yarn, and what it does.
Maybe we should look at that, if we are already making changes to our package manager setup...

**Comment by hesselberg** [comment]
I think we should stick to npm, and don't look at Yarn. Yarn is what... 3 weeks old? We don't know if they will abandon the project in a year or two.

Regarding bower, I agree, lets remove it, and replace everything with npm.

**Comment by hesselberg** [comment]
Lets push forward on this

**Comment by Dan9boi** [comment]
This i now merged and we have now skipped bower.
