### ISSUE TITLE
Why use spaces over tabs?

### ISSUE THREAD

**Issue by SergiSMJ** [Novicell/novicell-frontend#85]
Let's debate!

https://www.youtube.com/watch?v=SsoOG6ZeyUI

👾

**Comment by hesselberg** [comment]
Haha 👍 

Seriously though, spaces ;-)

**Comment by SergiSMJ** [comment]
My points are: 
- File size, with spaces is bigger
- Atom, Sublime and VS etc... they come by default with tabs (when you use the tab key)
- What is the point to use spaces? When the file is minimized delete all of the spaces & tabs

**Comment by Dan9boi** [comment]
@SergiSMJ regarding to the editor settings is should have been fixed with the #57 editorconfig. If not, then maybe create a new issue for this. 
Regarding the file size i think the difference is too little for this to be an real argument, due to the file size only will change in the repository, and not the final website, as we are minifying everything in production.

I really don't care, as long as we all do it the same way, but i know it's a big religion thing for people like @misterwinther :)

**Comment by hesselberg** [comment]
If noon else has any input, I'll close the issue
